- name: Installation of my web-server
  hosts: all
  tasks:
    - name: install web package
      package:
        name: httpd
        state: latest
      when: ansible_os_family == "RedHat"
  
    - name: install web package
      package:
        name: apache2
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: start httpd
      systemd:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"

    - name: start apache2
      systemd:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"
